services:
  exposure-calculation-agent:
    image: ghcr.io/theworldavatar/exposure-calculation-agent:2.4.0-24-add-authentication-for-timeline-SNAPSHOT
    build:
      context: .
      target: production
