PREFIX ies4: <http://ies.data.gov.uk/ontology/ies4#>

SELECT ?{VARNAME} ?start_time ?end_time
WHERE {{
  {VALUES_CLAUSE}

  ?startEvent  ies4:isStartOf  ?{VARNAME} ;
               ies4:inPeriod   ?startPeriod .

  ?startPeriod ies4:iso8601PeriodRepresentation  ?start_time .

  ?endEvent    ies4:isEndOf    ?{VARNAME} ;
               ies4:inPeriod   ?endPeriod .

  ?endPeriod   ies4:iso8601PeriodRepresentation  ?end_time .
}}
