CREATE TEMP TABLE {TEMP_TABLE} AS
SELECT ST_Transform({GEOMETRY_COLUMN}, 3857) AS wkb_geometry, {VALUE_COLUMN} AS val, {AREA_COLUMN} AS area
FROM {EXPOSURE_DATASET};

CREATE INDEX {TEMP_TABLE}_geom_gix
ON {TEMP_TABLE}
USING GIST (wkb_geometry);