PREFIX_EXPOSURE = 'https://www.theworldavatar.com/kg/ontoexposure/'
PREFIX_DCAT = 'http://www.w3.org/ns/dcat#'
PREFIX_DERIVATION = 'https://www.theworldavatar.com/kg/ontoderivation/'

# default columns from gdal
VECTOR_GEOMETRY_COLUMN = 'wkb_geometry'
RASTER_GEOMETRY_COLUMN = 'rast'

# predicates
# calculation metadata
HAS_DISTANCE = PREFIX_EXPOSURE + 'hasDistance'
HAS_UPPERBOUND = PREFIX_EXPOSURE + 'hasUpperbound'
HAS_LOWERBOUND = PREFIX_EXPOSURE + 'hasLowerbound'
HAS_DATASET_FILTER = PREFIX_EXPOSURE + 'hasDatasetFilter'
HAS_FILTER_COLUMN = PREFIX_EXPOSURE + 'hasFilterColumn'
HAS_FILTER_VALUE = PREFIX_EXPOSURE + 'hasFilterValue'

EXP_HAS_VALUE = PREFIX_EXPOSURE + 'hasValue'
DCTERM_TITLE = 'http://purl.org/dc/terms/title'
DATASET_PREDICATE = PREFIX_DCAT + 'dataset'
SERVES_DATASET = PREFIX_DCAT + 'servesDataset'
ENDPOINT_URL = PREFIX_DCAT + 'endpointURL'
IS_DERIVED_FROM = PREFIX_DERIVATION + 'isDerivedFrom'
BELONGS_TO = PREFIX_DERIVATION + 'belongsTo'
HAS_CALCULATION_METHOD = PREFIX_EXPOSURE + 'hasCalculationMethod'

# exposure dataset properties
HAS_GEOMETRY_COLUMN = PREFIX_EXPOSURE + 'hasGeometryColumn'
HAS_AREA_COLUMN = PREFIX_EXPOSURE + 'hasAreaColumn'
HAS_IRI_COLUMN = PREFIX_EXPOSURE + 'hasIriColumn'

# time series related
TIMESERIES_NAMESPACE = 'https://www.theworldavatar.com/kg/ontotimeseries/'
HAS_TIME_SERIES = TIMESERIES_NAMESPACE + 'hasTimeSeries'
TIMESERIES_TYPE = TIMESERIES_NAMESPACE + 'TimeSeries'
HAS_TIME_CLASS = TIMESERIES_NAMESPACE + 'hasTimeClass'
OBSERVATION_OF = TIMESERIES_NAMESPACE + 'observationOf'
HAS_RESULT = TIMESERIES_NAMESPACE + 'hasResult'
TS_HAS_VALUE = TIMESERIES_NAMESPACE + 'hasValue'

# types
DCAT_DATASET = PREFIX_DCAT + 'Dataset'
TRIP = PREFIX_EXPOSURE + 'Trip'
EXPOSURE_RESULT = PREFIX_EXPOSURE + 'ExposureResult'
DERIVATION = PREFIX_DERIVATION + 'Derivation'
POSTGIS_SERVICE = 'https://theworldavatar.io/kg/service#PostGIS'

TRAJECTORY_COUNT = PREFIX_EXPOSURE + 'TrajectoryCount'
TRAJECTORY_AREA = PREFIX_EXPOSURE + 'TrajectoryArea'
SIMPLE_COUNT = PREFIX_EXPOSURE + 'Count'
SIMPLE_AREA = PREFIX_EXPOSURE + 'Area'
AREA_WEIGHTED_SUM = PREFIX_EXPOSURE + 'AreaWeightedSum'
RASTER_COUNT = PREFIX_EXPOSURE + 'RasterCount'
TRAJECTORY_AREA_WEIGHTED_SUM = PREFIX_EXPOSURE + 'TrajectoryAreaWeightedSum'
TRAJECTORY_TIME_FILTER_COUNT = PREFIX_EXPOSURE + 'TrajectoryTimeFilterCount'
TRAJECTORY_TIME_FILTER_COUNT_DETAILED = PREFIX_EXPOSURE + \
    'TrajectoryTimeFilterCountDetailed'

TRAJECTORY_TYPES = [TRAJECTORY_COUNT,
                    TRAJECTORY_AREA, TRAJECTORY_AREA_WEIGHTED_SUM, TRAJECTORY_TIME_FILTER_COUNT, TRAJECTORY_TIME_FILTER_COUNT_DETAILED]
CALCULATION_TYPES = [SIMPLE_COUNT, SIMPLE_AREA,
                     AREA_WEIGHTED_SUM, RASTER_COUNT] + TRAJECTORY_TYPES

DATASET_FITLER = PREFIX_EXPOSURE + 'DatasetFilter'

BIND_MOUNT_PATH = '/app/queries/'  # needs to match with stack manager config

# units
METRE_SQUARED = 'm²'
