# functions that are shared between calculation types
from agent.calculation.calculation_input import CalculationInput
from shapely import wkt
from shapely.ops import transform
from pyproj import Transformer
from agent.utils import constants
from agent.utils.stack_configs import ONTOP_CLIENT
from twa import agentlogging
import re
from agent.utils.postgis_client import postgis_client
from psycopg2.extras import execute_values
from agent.utils.stack_gateway import stack_clients_view
from pathlib import Path
from agent.utils.constants import METRE_SQUARED, EXPOSURE_RESULT
import json
import time
import statistics
from scipy import stats
import pandas as pd

logger = agentlogging.get_logger('dev')

rdf_type_to_unit = {
    constants.TRAJECTORY_COUNT: '',
    constants.TRAJECTORY_AREA: METRE_SQUARED,
    constants.TRAJECTORY_AREA_WEIGHTED_SUM: METRE_SQUARED,
    constants.TRAJECTORY_TIME_FILTER_COUNT: '',
    constants.TRAJECTORY_TIME_FILTER_COUNT_DETAILED: ''
}


def instantiate_result_ontop(subject_to_value_dict: dict = None, calculation_input: CalculationInput = None):
    with postgis_client.connect() as conn:
        with conn.cursor() as cur:
            create_table = """
            CREATE TABLE IF NOT EXISTS exposure_result (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                subject TEXT,
                exposure TEXT,
                calculation TEXT,
                value double precision,
                unit TEXT,
                mean double precision,
                stddev double precision,
                z_score double precision,
                percentile double precision,
                CONSTRAINT exposure_result_constraint UNIQUE (subject, exposure, calculation)
            );
            """
            cur.execute(create_table)

            data = []

            if calculation_input.calculation_metadata.rdf_type not in constants.TRAJECTORY_TYPES:
                insert_query = """
                    INSERT INTO exposure_result (subject, exposure, calculation, value, unit, z_score, percentile, mean, sddev)
                    VALUES %s
                    ON CONFLICT (subject, exposure, calculation)
                    DO UPDATE SET value = EXCLUDED.value,
                                  unit = EXCLUDED.unit,
                                  z_score = EXCLUDED.z_score,
                                  percentile = EXCLUDED.percentile,
                                  mean = EXCLUDED.mean,
                                  sddev = EXCLUDED.sddev
                """
                values = [v.value for v in subject_to_value_dict.values()]
                mean = statistics.mean(values)
                sddev = statistics.stdev(values)

                subject_to_z_score = _get_z_score(
                    subject_to_result_dict=subject_to_value_dict, mean=mean, sddev=sddev)
                subject_to_percentile = _get_percentile(subject_to_value_dict)

                for subject, value in subject_to_value_dict.items():
                    data.append((subject, calculation_input.exposure,
                                calculation_input.calculation_metadata.iri, value.value, value.unit, subject_to_z_score[subject], subject_to_percentile[subject], mean, sddev))
            else:
                # trajectory case, only one subject
                data = [(calculation_input.subject, calculation_input.exposure,
                         calculation_input.calculation_metadata.iri, rdf_type_to_unit[calculation_input.calculation_metadata.rdf_type])]

                insert_query = """
                    INSERT INTO exposure_result (subject, exposure, calculation, unit)
                    VALUES %s
                    ON CONFLICT DO NOTHING
                """

            execute_values(cur, insert_query, data)

    # upload mapping only if it has not been uploaded
    logger.info('Uploading ontop mapping if it does not exist')
    _upload_ontop_mapping()


def _upload_ontop_mapping():
    from agent.utils.kg_client import kg_client

    # Don't make too general a query here. Look for a statement
    # that can be there only if the mapping has been uploaded.
    query = f"SELECT * WHERE {{?r a <{EXPOSURE_RESULT}>}} LIMIT 1"

    # currently fixed to the default ontop container
    query_result = json.loads(
        kg_client.ontop_client.executeQuery(query).toString())

    if not query_result:
        logger.info("Updating Ontop mapping...")
        ontop_mapping_path = Path('agent/calculation/resources/ontop.obda')

        path = stack_clients_view.java.nio.file.Paths.get(
            stack_clients_view.java.net.URI(ontop_mapping_path.resolve().as_uri()))
        ONTOP_CLIENT.updateOBDA(path)
        # Give Ontop some time to sort itself out.
        # It will not be ready immediately to take queries!
        time.sleep(30)
        # The following is essential. Otherwise the outgoing federation
        # will return nothing, or random garbage...
        of_rep_id = stack_clients_view.Rdf4jService.OUT_STACK_REPO_ID
        logger.info(f"Refreshing outgoing federation ('{of_rep_id}') cache...")
        stack_clients_view.Rdf4jClient.getInstance().refreshRepositoryCache(of_rep_id)
        time.sleep(5)


def get_iri_to_point_dict(subject):
    # returns points in EPSG:3857, to be used for ST_DWithin in queries
    from agent.utils.kg_client import kg_client
    if not isinstance(subject, list):
        subject = [subject]

    iri_to_point_dict = {}
    transformer = Transformer.from_crs(
        "EPSG:4326", "EPSG:3857", always_xy=True)

    query_template = """
    SELECT ?subject ?wkt
    WHERE {{
        VALUES ?subject {{{values}}}.
        ?subject <http://www.opengis.net/ont/geosparql#asWKT> ?wkt.
    }}
    """

    logger.info(
        'Querying geometries of subjects, number of subjects: ' + str(len(subject)))

    query_list = []
    # submit queries in batches to avoid crashing ontop
    for chunk in _chunk_list(subject):
        values = " ".join(f"<{s}>" for s in chunk)
        query = query_template.format(values=values)
        query_list.append(query)

    for query in query_list:
        query_result = json.loads(
            kg_client.remote_store_client.executeQuery(query).toString())

        for row in query_result:
            sub = row['subject']
            wkt_literal = row['wkt']

            # strip RDF literal IRI, i.e. ^^<http://www.opengis.net/ont/geosparql#wktLiteral>
            match = re.match(r'^"(.+)"\^\^<.+>$', wkt_literal)
            if match:
                geom = wkt.loads(match.group(1))
            else:
                geom = wkt.loads(wkt_literal)

            projected_geom = transform(transformer.transform, geom)
            iri_to_point_dict[sub] = projected_geom

    return iri_to_point_dict


def get_iri_to_buffer_dict(subject, distance: float):
    # returns buffers in 4326
    from agent.utils.kg_client import kg_client

    iri_to_buffer_dict = {}
    transformer = Transformer.from_crs(
        "EPSG:4326", "EPSG:3857", always_xy=True)

    transformer_back = Transformer.from_crs(
        "EPSG:3857", "EPSG:4326", always_xy=True)

    query_template = """
    SELECT ?subject ?wkt
    WHERE {{
        VALUES ?subject {{{values}}}.
        ?subject <http://www.opengis.net/ont/geosparql#asWKT> ?wkt.
    }}
    """

    logger.info(
        'Querying geometries of subjects, number of subjects: ' + str(len(subject)))

    query_list = []
    # submit queries in batches to avoid crashing ontop
    for chunk in _chunk_list(subject):
        values = " ".join(f"<{s}>" for s in chunk)
        query = query_template.format(values=values)
        query_list.append(query)

    for query in query_list:
        query_result = json.loads(
            kg_client.remote_store_client.executeQuery(query).toString())

        for row in query_result:
            sub = row['subject']
            wkt_literal = row['wkt']

            # strip RDF literal IRI, i.e. ^^<http://www.opengis.net/ont/geosparql#wktLiteral>
            match = re.match(r'^"(.+)"\^\^<.+>$', wkt_literal)
            if match:
                geom = wkt.loads(match.group(1))
            else:
                geom = wkt.loads(wkt_literal)

            projected_geom = transform(transformer.transform, geom)
            buffered_geom = projected_geom.buffer(distance)
            iri_to_buffer_dict[sub] = transform(
                transformer_back.transform, buffered_geom)

    return iri_to_buffer_dict


def _get_z_score(subject_to_result_dict: dict, mean, sddev):
    subject_to_z_score = {}

    for subject in subject_to_result_dict:
        subject_to_z_score[subject] = (
            subject_to_result_dict[subject].value - mean) / sddev

    return subject_to_z_score


def _get_percentile(subject_to_result_dict: dict):
    # extract numerical value out of ExposureValue
    subject_to_value_dict = {}
    for subject in subject_to_result_dict:
        subject_to_value_dict[subject] = subject_to_result_dict[subject].value

    dataframe = pd.Series(subject_to_value_dict)

    percentiles = dataframe.rank(method="max", pct=True) * 100

    return percentiles.to_dict()


def _chunk_list(values, chunk_size=10000):
    for i in range(0, len(values), chunk_size):
        yield values[i:i + chunk_size]
